### ISSUE TITLE
How to enable (Toggle to right side ) by default when activity creates using code

### ISSUE THREAD

**Issue by anand-010** [sparrow007/CustomToggleButton#4]

**Comment by sparrow007** [comment]
Thanks for reporting the issue regarding this library, will update this library for method to switch default to either left or right.

**Comment by anand-010** [comment]
Thank you for your quick response. I am waiting for the pr

**Comment by anand-010** [comment]
no new Updates ?

**Comment by anand-010** [comment]
@sparrow007 please add these feature immediately
